### ISSUE TITLE
10-1-2022 is missing

### ISSUE THREAD

**Issue by syedsohan** [FrancescoXX/100-days-of-Web3#1]
Here, `10-1-2022` is missing
![Screenshot_1](https://user-images.githubusercontent.com/63908584/146745332-99c66e7d-acb3-4744-9910-9d5e20b165fb.png)

If we add 10-1-2022 then there will be no need for 29-3-2022. You can end your streak of 100-days-of-Web3 at 28-3-2022.

**Comment by syedsohan** [comment]
@FrancescoXX if you want I can add 10-1-2022.

**Comment by FrancescoXX** [comment]
nice catch, thank you! go for that if you want!

**Comment by syedsohan** [comment]
> nice catch, thank you! go for that if you want!

I have updated the README.md #2
