### ISSUE TITLE
docs: Add LICENCE

### ISSUE THREAD

**Issue by Pradumnasaraf** [FrancescoXX/100-days-of-Web3#11]
![Screenshot from 2022-04-01 18-22-19](https://user-images.githubusercontent.com/51878265/161267504-b408667a-760c-429b-a34b-22c4c4350d83.png)

**Comment by FrancescoXX** [comment]
Solved!

https://github.com/FrancescoXX/100-days-of-Web3/commit/32f26bcbf73b729cfc633253d3ffa4767e8cd507
